name: correct_speech
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  dart_frog_gen: ^0.3.2
  dart_frog_web_socket: ^0.1.0-dev.3

  drift: ^2.6.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.0
  path: ^1.8.3
  injector: ^2.0.0
  equatable: ^2.0.5
  sqlite3: ^1.10.1
  broadcast_bloc: ^0.1.0-dev.2

  


dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2

  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  lints: ^2.0.1
  drift_dev: ^2.6.0
