name: correct_speech
description: Оптимизирует процессы работы логопеда

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  injector: ^2.0.0
  floor: ^1.4.1
  json_annotation: ^4.8.0
  material_design_icons_flutter: ^6.0.7096
  flutter_native_splash: ^2.2.9
  path_provider: ^2.0.14
  video_thumbnail: ^0.5.3
  file_picker: ^5.2.6
  path: ^1.8.1
  shared_preferences: ^2.1.0
  permission_handler: ^10.2.0
  photo_manager: ^2.6.0
  equatable: ^2.0.5
  web_socket_channel: ^2.3.0
  broadcast_bloc: ^0.1.0-dev.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  build_runner: ^2.3.3
  floor_generator: ^1.3.0
  bloc_test: ^9.1.1
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true
  assets:
    - assets/features_icons/

